In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 12s 12s/step
[[0.00387559 0.10973547 0.67105305 0.21533592]]
1/1 [==============================] - 0s 41ms/step
[[0.01118432 0.40648288 0.20074137 0.38159147]]
1/1 [==============================] - 0s 49ms/step
[[0.01827021 0.54511374 0.15444462 0.28217137]]
1/1 [==============================] - 0s 45ms/step
[[0.01409299 0.37419274 0.19863899 0.41307533]]
1/1 [==============================] - 0s 43ms/step
[[0.01228736 0.37499294 0.27157587 0.34114382]]
1/1 [==============================] - 0s 38ms/step
[[0.00957527 0.23710068 0.47431308 0.27901107]]
1/1 [==============================] - 0s 62ms/step
[[0.01097733 0.37239745 0.1603714  0.45625383]]
1/1 [==============================] - 0s 36ms/step
[[0.01439996 0.5409741  0.20178996 0.24283601]]
1/1 [==============================] - 0s 50ms/step
[[0.01458517 0.5713423  0.13853961 0.2755329 ]]
1/1 [==============================] - 0s 55ms/step
[[0.01262704 0.43503597 0.19754922 0.3547878 ]]
