In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print("\nthis is the prediction:^" + prediction + "^")
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 5s 5s/step
[[0.001043   0.00349836 0.9942052  0.00125347]]
1/1 [==============================] - 0s 43ms/step
[[0.00710481 0.00941948 0.9720986  0.01137719]]
1/1 [==============================] - 0s 47ms/step
[[0.00469505 0.00758826 0.97857726 0.00913941]]
1/1 [==============================] - 0s 55ms/step
[[0.00304885 0.00830968 0.9811344  0.00750712]]
1/1 [==============================] - 0s 43ms/step
[[0.00416744 0.00921609 0.9773193  0.00929722]]
1/1 [==============================] - 0s 49ms/step
[[0.00332176 0.0076293  0.97987205 0.009177  ]]
1/1 [==============================] - 0s 49ms/step
[[0.00499904 0.01286736 0.97089976 0.01123381]]
1/1 [==============================] - 0s 50ms/step
[[0.0043209  0.00879684 0.97736245 0.00951983]]
1/1 [==============================] - 0s 45ms/step
[[0.00461186 0.01009338 0.9779116  0.00738309]]
1/1 [==============================] - 0s 43ms/step
[[0.00670391 0.01206492 0.9686471  0.01258405]]
1/